version: "3.3"

services:
  backend:
    image: jeffery426/shoppingcart_backend:latest  # ✅ 直接從 Docker Hub 拉取
    container_name: django-backend
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      # - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      # - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_API_URL_ADMIN_CHECKLOGIN=${BACKEND_API_URL_ADMIN_CHECKLOGIN}
      - BACKEND_API_URL_ADMIN_LOGIN=${BACKEND_API_URL_ADMIN_LOGIN}
      - BACKEND_API_URL_ADMIN_LOGOUT=${BACKEND_API_URL_ADMIN_LOGOUT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    depends_on: []  # 🔹 因為 MySQL 在外部，所以不再依賴 `db`
    env_file:
      - .env
    networks:
      - shoppingcart-network

  frontend:
    image: jeffery426/shoppingcart_frontend:latest  # ✅ 直接從 Docker Hub 拉取
    container_name: react-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    volumes:
      - static_volume:/usr/share/nginx/html/static
    env_file:
      - .env
    networks:
      - shoppingcart-network

volumes:
  static_volume:
networks:
  shoppingcart-network:
