# Generated by Django 5.1.6 on 2025-02-25 09:13

from django.db import migrations

def add_admin_data(apps, schema_editor):
    # 獲取 Admin 模型
    Admin = apps.get_model('shop', 'Admin')  # 替換 'app_name' 為您應用的名稱

    # 插入資料
    Admin.objects.create(acc_name='root', password='root')

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_admin_data),  # 這會執行您上面寫的函數
    ]
    
