# Generated by Django 5.1.6 on 2025-02-25 09:24

from django.db import migrations
def add_footer_data(apps, schema_editor):
    # 獲取 Product 模型
    Product = apps.get_model('shop', 'Footer')  # 確保 'shop' 是應用名稱

    # 插入多個產品資料
    Product.objects.create(
        about_us = '111502522劉俊吾',
        contact_us = 'a4264428@gmail.com'
    )
    

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_add_product_data'),
    ]

    operations = [
        migrations.RunPython(add_footer_data),  # 執行添加產品資料的函數
    ]
